dist: trusty
services:
  - docker
before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/Dockerfile -t chemistry .
script:
  - docker run -it chemistry python3 -c "import paccmann_chemistry"
  - docker run -it chemistry python3 -m unittest discover -t . -p "test_*py" paccmann_chemistry
  - docker run -it chemistry python3 examples/train_vae.py -h
notifications:
  slack:
    secure: AEVxdiVh+ysijnz8uLuPX6sBYiXDeEK/kbZ02N/irM5txclPrQZsYDjqCA0TcynYBY/0zPrv3IWh3dPcnFd8vU8DMRPeXqkt8GzjH1CDzr9MLDibcHjf2M7jcpLmYrK4OVUWOxRNZvQEs6bkxKVxNM7OtJAMd0PEZ4MC3LXBcCaVGDQE0keiywhK0yk5YZQAf4X2qpIduRK6pShXd7vKJ/E9ubEI+fACgbsCQ6BxL3NKaHKDedj3MJxxOZMjFftQCgRakOdCNi372WuniN2L8Q47RRMv676kvVvB3DIZK39GIJuO7JTgJhtS6iZzSRsrLIwWAk3RwIts2qRSKaYZ53rt9FQb0Ie7jSOpWV0Qts8jLU2LluaF6rJt/jyIp08ABQ5WuMfEnYLMpSqSF/Rn/I21r1DEuLeaNNgtNzQoENkayL+PeWf11gqGh/EbqEiyUNg8wluVeGr6SoWXyhPJM/qlbx2dDix01wZCrRbOy3DKVzzZaaV5kRCTJC/J5lYn9ZNk1xFZ3oQh0wAuBxIcnDnciDxjdQnD7eTkFYhizZ8HOGBZDP1LvmhW3h4e1YHfuKK71eiK1VQk0Lo8aC3yUoBLVzwdvlyE6Vvt5mP3pniEb0Nkd8BfXB28s+IQnCvZfI+QsFD07LIjGKP78R/UbDxMfvRAwHcdj8WWBuP+gjY=
