dist: trusty

services:
  - docker

before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/Dockerfile -t chemistry .

script:
  - docker run -it chemistry python3 -c "import paccmann_chemistry"
  - docker run -it chemistry python3 examples/train_vae.py -h
