name: paccmann_chemistry
channels:
  - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2019.03.1
  - python>=3.6,<3.8
  - pip>=19.1
  - pip:
      - pytoda @ git+https://git@github.com/PaccMann/paccmann_datasets@latest
      - numpy>=1.14.3
      - absl-py>=0.8.1
      - torch>=1.0.1
